# Generated by Django 4.0.1 on 2022-02-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('sr', models.IntegerField()),
                ('c_name', models.CharField(max_length=50)),
                ('c_course_comp', models.FloatField()),
                ('c_course_entc', models.FloatField()),
                ('c_course_civil', models.FloatField()),
                ('c_course_mech', models.FloatField()),
                ('c_course_chem', models.FloatField()),
                ('c_course_other', models.FloatField(max_length=50)),
                ('c_info', models.CharField(max_length=50)),
            ],
        ),
    ]
