# Generated by Django 4.0.1 on 2022-02-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_userfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='myecf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('autonomus_status', models.CharField(max_length=15)),
                ('university', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=20)),
                ('reservation', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('min_cet', models.FloatField()),
                ('min_jee', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='college',
        ),
    ]
