# Generated by Django 3.2.9 on 2022-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_myecf_delete_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='myecf',
            name='clg_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myecf',
            name='clg_short_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
